import { useForm } from "react-hook-form";
import * as z from "zod";
import {
    Card,
    CardHeader, 
    CardContent,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
    Form,
    FormField,
    FormControl,
    FormDescription,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";
import { CardWrapper } from "../auth/card-wrapper";
import { zodResolver } from "@hookform/resolvers/zod";
import { LoginSchema } from "@/schemas";
import { Input } from "@/components/ui/input";

export default function HemogramaCom(){
    const form = useForm<z.infer<typeof LoginSchema>>({
        resolver: zodResolver(LoginSchema),
        defaultValues:{
            email:"",
            password:"",
        }  
    });

    return(
        <div className="flex items-center justify-center min-h-screen bg-white">
            <CardWrapper
            headerTitle="Um novo Exame"
            headerLabel="Colesterol Total e Fracionado"
            backButtonHref="/add-exame"
            backButtonLabel="Não tenho nada para registrar"
        >
            <Form {...form}>
                <form 
                    className="space-y-6"
                >
                    <div className="max-h-96 overflow-y-auto">
                        <div className=" ">
                            <span>Eritograma</span>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Hemacias</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Hemoglobina</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Hematócrito</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>VCM</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>HCM</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>CHCM</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>RDW</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <span>Leucograma</span>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Leucograma Global</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Neutrófilos Segmentados</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Eosinóflos</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Basófilos</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Linfócitos Típicos</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Monócitos</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <span>Plaquetas</span>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>Contagem</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>VPM</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>PDW</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                            <FormField 
                            control={form.control}
                            name="email"
                            render={({field})=>(
                                <FormItem>
                                    <FormLabel>PCT</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder=""
                                        />
                                    </FormControl>
                                </FormItem>
                            )}>
                            </FormField>
                        </div>
                    </div>
                </form>
            </Form>
        </CardWrapper>
        </div>
    )
}